### ISSUE TITLE
How can I use testing your code inside of Visual Studio

### ISSUE THREAD

**Issue by rheid** [seekdavidlee/Eklee-Azure-Functions-GraphQl#53]
HI ENG-KEONG DAVID LEE,

thanks for writing such a great libary for Azure Functions. I am thinking about using it in a project. I would like to work with automatic tests after this example:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-test-a-function

Unfortunately I cannot call GraphQLFunction.Run because the ExecutionContext is missing in the test case. Do you have an idea how to do this best with Azure V3? or should I rather use your client?
        [Fact]
        [ExecutionContextDependencyInjection(typeof(FunctionModule))]
        public async void Http_trigger_should_return_known_string()
        {
            var request = TestFactoryPages.CreateHttpRequest("name", "Bill");
            **ExecutionContext ex = new ExecutionContext();**

            var response = (OkObjectResult)await GraphQLFunction.Run(request, logger, **ex**);
            Assert.Equal("Hello, Bill", response.Value);

        }

**Comment by seekdavidlee** [comment]
Hello,

I would suggest running integration tests directly by running the Azure Functions and using postman to trigger your GraphQL endpoint with various payloads. You can refer to the example I have in https://github.com/seekdavidlee/Eklee-Azure-Functions-GraphQl/blob/master/cicd.ps1. azure-functions-core-tools@3 is used to run the Azure Function locally and newman is used to run postman tests. This uses npm and doesn't require Visual Studio.

If you have the postman app (https://www.postman.com/downloads/), you can review the example I have in https://github.com/seekdavidlee/Eklee-Azure-Functions-GraphQl/blob/master/Tests/Eklee.Azure.Functions.GraphQl.postman_collection.json

Hope this helps. Happy coding!

David Lee

**Comment by seekdavidlee** [comment]
Closing this issue as there has been no activities.
