### ISSUE TITLE
problems with nullable query variables

### ISSUE THREAD

**Issue by rheid** [seekdavidlee/Eklee-Azure-Functions-GraphQl#67]
Hi David Lee, thanks for the quick help in the other two points. i still have a small issue. we are using an apollo server with a UI framework in the frontend. Here it is so that an unused filter sets the variable to null or does not pass it. like this:

Do you have an idea how I can allow a query variable to be null and then ignore this filter?

```
{
    "after": "",
    "audiences": "100000005,100000004,100000008",
    "between": "2021-01-01T00:00:00,2021-07-31T24:00:00",
    "language": "1033",
    "maintopics": "-",
    "place": "On-site",
    "name": " ",
    "navigation": "-",
    "pageSize": 15
}
```

```
query ($navigation: String, $name: String, $maintopics: String, $audiences: String!,
 $language: String!, $pageSize: Int!, $after: String, $between: String, $place: String) {
  getEvent(
    navigation: {contains: $navigation}
    name: {contains: $name}
    place: {contains: $place}
    language: {contains: $language}
    audiences: {contains: $audiences}
    maintopics: {contains: $maintopics}
    first: $pageSize
    after: $after
    datestart: {contains: $between}
  ) {
    totalCount
    items {
      id
      name
      url
      editor
      navigation
      leadimageUrl
      audiences
      language
      createdOn
      mainTopics
      topic2NdValue
      topic3NdValue
      thumbnail
      abstract
      venue
      place
      fees
      dateStart
      dateEnd
      layoutContent
      __typename
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
      __typename
    }
    __typename
  }
}
```

I the the following error if a query variable is null or not  present.

```
{
    "data": {
        "getEvent": null
    },
    "errors": [
        {
            "message": "Error trying to resolve getEvent.",
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ],
            "path": [
                "getEvent"
            ],
            "extensions": {
                "code": "NULL_REFERENCE"
            }
        }
    ]
}
```

**Comment by rheid** [comment]
@seekdavidlee  the server make the variables like this or did not set variables like maintopics 

{
    "after": "",
    "audiences": "100000005,100000004,100000008",
    "between": "2021-01-01T00:00:00,2021-07-31T24:00:00",
    "language": "1033",
    **"place": null,**
    "name": ,
    **"navigation": null,**
    "pageSize": 15
}

**Comment by rheid** [comment]
@seekdavidlee do thing for this topic a solution is possible?

**Comment by seekdavidlee** [comment]
@rheid - Can you completely remove? In the example below, place and navigation is missing. I think it would be confusing to continue to have a variable there and set it to null to indicate that this is an optional parameter.

query ($name: String, $maintopics: String, $audiences: String!,
 $pageSize: Int!, $after: String, $between: String, $place: String) {
  getEvent(
    name: {contains: $name}
    language: {contains: $language}
    audiences: {contains: $audiences}
    maintopics: {contains: $maintopics}
    first: $pageSize
    after: $after
    datestart: {contains: $between}
  )

**Comment by rheid** [comment]
Hi David,

Thanks for your feedback! What you wrote is totally understandable for me. Unfortunately it is so that the next nextJS https://nextjs.org/ the graph Qi query statically code. If a filter does not come to use on the web page the framework is set the variables to null by nextJS. The omission of optional parameters is not so simple because it goes past the ideas of the framework.

I can take over the implementation also gladly myself I would need however a ideal form you in which classes you see this. You can think about it later if you want to merge this code to your solution. 

Have a nice sunday and see you soon. Best Ralf

**Comment by seekdavidlee** [comment]
Hi @rheid - You can take a look at ContextValueResolver.cs and look at line 33. Change from

```
contextValue.Values = new List<object> { arg.First().Value };
```
To
```
var val = arg.First().Value;
if (modelMember.IsOptional && val == null) return contextValue;

contextValue.Values = new List<object> { val };
```

**Comment by rheid** [comment]
@seekdavidlee  Fantastic that runs exactly as I've been looking for. Thank you very much. You might want to include this in Master as well.
